import type { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { apiReference } from '@scalar/nestjs-api-reference';

export function setupApiDocs(app: INestApplication<any>) {
  //? Swagger setup
  const swaggerConfig = new DocumentBuilder()
    .setTitle(process.env.npm_package_name ?? 'API Documentation')
    .setDescription(
      process.env.npm_package_description ??
        'API documentation generated by Swagger',
    )
    .setVersion(process.env.npm_package_version ?? '1.0')
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, swaggerConfig);

  SwaggerModule.setup('api', app, document, {
    swaggerUiEnabled: false, //? Disable Swagger UI since we're using Scalar UI
  });

  // Scalar UI at /docs
  app.use(
    '/docs',
    apiReference({
      content: document,
      layout: 'modern',
      theme: 'kepler',
      hideClientButton: true,
      showOperationId: true,
      showSidebar: true,
      showDeveloperTools: 'never',
      operationTitleSource: 'summary',
      persistAuth: true,
      telemetry: true,
      isEditable: false,
      isLoading: false,
      documentDownloadType: 'both',
      hideSearch: false,
      withDefaultFonts: true,
      defaultOpenFirstTag: true,
      defaultOpenAllTags: true,
      expandAllModelSections: false,
      expandAllResponses: false,
      orderSchemaPropertiesBy: 'alpha',
      orderRequiredPropertiesFirst: true,
      _integration: 'nestjs',
      default: false,
    }),
  );
}
